### ISSUE TITLE
requests.get() takes exactly 1 argument (2 given) - Python 2.7.6

### ISSUE THREAD

**Issue by tribunal** [tgrosch/zdf-auto-dl#1]
Hi,

when i run "./main.py -f -c /tmp/zdf.ini" i get the following error:

--- Error START ---
2016-11-05 14:29:59,835 [WARNING] config.content.Configuration._get_value:44 No option 'speed' in section: 'user'
2016-11-05 14:29:59,836 [WARNING] config.content.Configuration._get_value:44 No option 'finished' in section: 'user'
2016-11-05 14:29:59,836 [ERROR] ..main.main:70 get() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "./main.py", line 61, in main
    execute(arguments)
  File "./main.py", line 49, in execute
    downloader.start()
  File "/tmp/zdf-auto-dl/src/zdf_auto_dl/action/file.py", line 93, in start
    self._download_show(show)
  File "/tmp/zdf-auto-dl/src/zdf_auto_dl/action/file.py", line 106, in _download_show
    result = requests.get(self.SEARCH_URL, show_data)
TypeError: get() takes exactly 1 argument (2 given)
--- Error END ---

I ran 'pip install -U -r requirements.txt' successfully on Python 2.7.6 (Ubuntu Server 14.04 LTS)

--- zdf.ini START ---
[user]
\# SHOWS: e.g. zdf heute,leute heute
shows=neo magazin royale,heute-show,die anstalt

\# MEDIA DIRECTORY: /home/user/zdf
media_dir=/tmp/zdf

\# FILENAME placeholders: show, season, episode, format, date
filename=S{season}E{episode}.{format}

\# SPEED LIMIT: e.g. 250KB/s
\#speed=250

\# PREVIOUS: load additional previous episodes (minimum: 1, default: 1)
previous=3

\# FINISHED: script to be executed after finishing a download, placeholders: see FILENAME
\#finished=/home/user/some-script.sh "{show}" "S{season}E{episode} vom {date}"
--- zdf.ini END ---

Any ideas how i can fix this ?

**Comment by neatc0der** [comment]
Hi Tribunal,

thank you for reporting this bug. Apparently there is an inconsistency of the requests API comparing python 2 and 3. I guess using urllib to serialize the data into a single address (meaning: https://www.zdf.de/suche **?q=<show>&contentTypes=episode**) should fix this problem.

I can either fix it later this weekend or you can create a pull request if you like.

Cheers,
T

**Comment by neatc0der** [comment]
Hi @tribunal,

so, I couldn't replicate your error, but I might have an idea to resolve the issue.

The troubling method has an own entry in the [requests documentation](http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls). I believe I made a mistake by defining the call without an explicit use of the keyword parameter `params`. I've fixed that and in addition you should check out the updated `pip install` command (see `-U`).

For me there was no problem during execution in general. Nevertheless I've found another bug concerning the use of `-f`/`--find`. Loggers now print to stderr while other output is printed to stdout. Thus requested output should be found much more easy (e.g. `./src/zdf_auto_dl/main.py -f 2> /dev/null`).

Cheers,
T
