### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by pfmephisto** [tgrosch/zdf-auto-dl#2]
hi,

I'm getting the following error after successfully running pip install -Ur requirements.txt and changing the download path in the config file.

Was wondering if you have any idea what could be causing it.

I'm running Debian (Jessie) with Python 2.7.9

----Start-Error----
2017-01-24 21:14:32,263 [ERROR] ..main.main:71 ConfigParser instance has no attribute 'read_file'
Traceback (most recent call last):
  File "./main.py", line 62, in main
    execute(arguments)
  File "./main.py", line 47, in execute
    config = ConfigurationLoader.get_config(arguments)
  File "/opt/zdf-auto-dl/src/zdf_auto_dl/config/loader.py", line 37, in get_config
    config_parser.read_file(config_fp)
AttributeError: ConfigParser instance has no attribute 'read_file'
----End-Error----

**Comment by neatc0der** [comment]
Hi @pfmephisto,

thanks for the feedback. Apperently there is a differing API for ConfigParser concerning python2 and python3. It's been a few days. Do you have any suggestions? Otherwise I might take a look at it later on.

Cheers!

**Comment by neatc0der** [comment]
OK, so I shortly read into the topic and found out that the method now called `read_file` was renamed in python 3.2 from `reafp`. I've added a detection for this method.

It should work now. Can you verify that?

**Comment by pfmephisto** [comment]
thanks. looking good so far
